     if(b[i][j]==1)
                    {
                        b[i][j]=0;
                    }
                    else
                    {
                        b[i][j]=1;
                    }

                    if(b[i+1][j]==1)
                    {
                        b[i+1][j]=0;
                    }
                    else
                    {
                        b[i+1][j]=1;
                    }

                    if(b[i-1][j]==1)
                    {
                        b[i-1][j]=0;
                    }
                    else
                    {
                        b[i-1][j]=1;
                    }

                    if(b[i][j+1]==1)
                    {
                        b[i][j+1]=0;
                    }
                    else
                    {
                        b[i][j+1]=1;
                    }
                    if(b[i][j-1]==1)
                    {
                        b[i][j-1]=0;
                    }
                    else
                    {
                        b[i][j-1]=1;
                    }